apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: consoledot-frontend-build-tests
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: consoledot-frontend-build-tests
    app.kubernetes.io/part-of: rhtap-consoledot-frontend-build
  name: consoledot-frontend-build-tests
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: consoledot-frontend-build-tests
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: consoledot-frontend-build-tests
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-migration-tenant/rhtap-consoledot-frontend-build/consoledot-frontend-build-tests@sha256:475b8f3e6bc5c078abc8c1f8b686ada98a4e7ab82430394fe724daefc7ead27a
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
