apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rhtap-consoledot-frontend-build-tests
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-migration-tenant/rhtap-consoledot-frontend-build/rhtap-consoledot-frontend-build-tests@sha256:a4a32fb1bacd11253efa5eba45ea900bb5e4006f3a5f17ad154d5d554e8abf68
        name: my-nodejs
        resources: {}
status: {}
