apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rhtap-consoledot-frontend-build-tests
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-migration-tenant/rhtap-consoledot-frontend-build/rhtap-consoledot-frontend-build-tests@sha256:66f9cf16395dec5b52b4ebbc81cd28bacb70779aedb26ac520581e10c4f55582
        name: my-nodejs
        resources: {}
status: {}
