apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: consoledot-frontend-build-tests
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-migration-tenant/rhtap-consoledot-frontend-build/consoledot-frontend-build-tests@sha256:de7c5477dff080030aed37450e81582a41b29828f00b4d5d822df6dab6b04879
        name: my-nodejs
        resources: {}
status: {}
