apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: consoledot-frontend-build-tests
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-migration-tenant/rhtap-consoledot-frontend-build/consoledot-frontend-build-tests@sha256:d7d802072cf7c72ec34e7b8c20619946dd250757fbe420886daa69c7a97cb98f
        name: my-nodejs
        resources: {}
status: {}
