apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: consoledot-frontend-build-tests
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-migration-tenant/rhtap-consoledot-frontend-build/consoledot-frontend-build-tests@sha256:475b8f3e6bc5c078abc8c1f8b686ada98a4e7ab82430394fe724daefc7ead27a
        name: my-nodejs
        resources: {}
status: {}
