apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rhtap-consoledot-frontend-build-tests
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhtap-consoledot-frontend-build-tests
    app.kubernetes.io/part-of: rhtap-consoledot-frontend-build
  name: rhtap-consoledot-frontend-build-tests
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: rhtap-consoledot-frontend-build-tests
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: rhtap-consoledot-frontend-build-tests
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-migration-tenant/rhtap-consoledot-frontend-build/rhtap-consoledot-frontend-build-tests@sha256:f2fcbdb36bcf5cf5fa0297d9c2873102d8631369e02f2f3d45397672da47b82f
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
